name: Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY]: "
labels: ["security", "urgent"]
assignees:
  - andrewHermann
body:
  - type: markdown
    attributes:
      value: |
        🚨 **SECURITY NOTICE**: If this is a critical security vulnerability, please contact the repository owner directly instead of filing a public issue.
  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Describe the vulnerability in detail
      placeholder: What is the security issue?
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: 1. Go to... 2. Click on... 3. See error...
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - Authentication System
        - Admin Panel
        - API Endpoints
        - Database Access
        - File System
        - Network Configuration
        - User Input Handling
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve by exploiting this vulnerability?
    validations:
      required: true
