name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Auto-label PR
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

    - name: Add size labels
      uses: pascalgn/size-label-action@v0.4.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sizes: >
          {
            "0": "XS",
            "20": "S", 
            "50": "M",
            "100": "L",
            "500": "XL"
          }
